let express=require("express")
const { reg, login, sendotp, resetpwd } = require("../controllers/usercont")
const { upload, addprod, prods, upddet, updimg, delprod, getprods } = require("../controllers/prodcont")
const { addcart, getcart, delcart, incqty, decqty } = require("../controllers/cartcon")
let rt=new express.Router()
rt.post("/reg",reg)
rt.post("/login",login)
rt.get("/sendotp/:id",sendotp)
rt.post("/resetpwd",resetpwd)
rt.post("/addprod",upload.single("img"),addprod)
rt.get("/prods",prods)
rt.post("/upddet",upddet)
rt.post("/updimg",upload.single("img"),updimg)
rt.delete("/delprod/:pid",delprod)
rt.get("/getprod/:pid",getprods)
rt.post("/addcart",addcart)
rt.get("/getcart/:uid",getcart)
rt.delete("/delcart/:id",delcart)
rt.get("/incqty/:id",incqty)
rt.get("/decqty/:id",decqty)
module.exports=rt